import Head from 'next/head'
import { useAppDispatch, useAppSelector } from '@/hooks/useApp'
import { useData } from '@/hooks/useData'
import { deleteTodo, updateTodo, createTodo } from "@/connector/crud"
import { getAllTodos } from "@/store/todolistSlice"
import TaskList from '@/components/taskList/TaskList'
import Submitter from '@/components/Submitter'
import TaskHeader from '@/components/taskList/TaskHeader'
import ProcessCard from '@/components/ProgressCard'

export default function Home() {

  const todos = useAppSelector((state)=>state.todos)
  const filter = useAppSelector((state)=>state.filter)
  const dispatch = useAppDispatch()

  useData(dispatch, getAllTodos)
  
  return (
    <>
      <Head>
        <title>Todos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main-container'>
        <div className='card-container'>
          <ProcessCard todos={todos}/>
          <TaskHeader dispatch={dispatch} filter={filter}/>
          <TaskList todos={todos} deleteTodo={deleteTodo} updateTodo={updateTodo} dispatch={dispatch}/>
          <Submitter createTodo={createTodo} placeholder='Add your todo...'/>
        </div>
      </main>
    </>
  )

}
